FROM node:16.13-alpine3.14 as builder

RUN npm install -g @nestjs/cli@8.2.0

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node package*.json ./

RUN npm install

COPY --chown=node . .

RUN npm run build

EXPOSE 3000

CMD [ "npm", "run", "start" ]

##CMD ["tail", "-f", "/dev/null"]
